server:
  port: 24110

spring:
    data:
      redis:
        host: localhost
        port: 6379
        repositories:
          enabled: false

    jpa:
      hibernate:
        ddl-auto: create-drop
      show-sql: false
      properties:
        hibernate:
          dialect: org.hibernate.dialect.PostgreSQLDialect


    datasource:
      url: jdbc:postgresql://localhost:5432/distcomp
      username: postgres
      password: 12345678
      driver-class-name: org.postgresql.Driver

